# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com

dist: packages

builds:
  - binary: generate-secure-pillar
    goos:
      - windows
      - darwin
      - linux
      - openbsd
      - netbsd
      - freebsd
    goarch:
      - amd64
      - arm64

archives:
  - id: main
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      openbsd: OpenBSD
      netbsd: NetBSD
      freebsd: FreeBSD
      amd64: x86_64
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

snapshot:
  name_template: SNAPSHOT-{{.Commit}}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  - # Repository to push the tap to.
    tap:
      owner: esilva-everbridge
      name: homebrew-generate-secure-pillar

    skip_upload: false

    dependencies:
      - gpg1

    # Git author used to commit to the repository.
    # Defaults are shown.
    commit_author:
      name: Ed Silva
      email: ed.silva@everbridge.com

    # Folder inside the repository to put the formula.
    # Default is the root folder.
    folder: Formula

    # Your app's homepage.
    # Default is empty.
    homepage: https://github.com/Everbridge/generate-secure-pillar

    # Your app's description.
    # Default is empty.
    description: "Create and update encrypted content or decrypt encrypted content in YAML files"

nfpms:
  - # Your app's vendor.
    # Default is empty.
    vendor: Everbridge, Inc.
    # Your app's homepage.
    # Default is empty.
    homepage: https://github.com/Everbridge/generate-secure-pillar

    # Your app's maintainer (probably you).
    # Default is empty.
    maintainer: "Ed Silva <ed.silva@everbridge.com>"

    # Your app's description.
    # Default is empty.
    description: "Create and update encrypted content or decrypt encrypted content in YAML files"

    # Your app's license.
    # Default is empty.
    license: MIT

    # Formats to be generated.
    formats:
      - deb
      - rpm

signs:
  - cmd: gpg
    artifacts: checksum
    args:
      [
        "-u",
        "Everbridge Open Source",
        "--output",
        "${signature}",
        "--detach-sign",
        "${artifact}",
      ]
