profiles:
  - name: dev
    default: true
    default_key: Dev Salt Master
    gnupg_home: ~/.gnupg

  - name: stage
    default: false
    default_key: Stage Salt Master
    gnupg_home: ~/.gnupg

  - name: prod
    default: false
    default_key: Prod Salt Master
    gnupg_home: ~/.gnupg
