project_name: generate-secure-pillar
release:
  github:
    owner: Everbridge
    name: generate-secure-pillar
  name_template: '{{.Tag}}'
brew:
  name: generate-secure-pillar
  github:
    owner: esilva-everbridge
    name: homebrew-tap
  commit_author:
    name: Ed Silva
    email: ed.silva@everbridge.com
  folder: Formula
  install: bin.install "generate-secure-pillar"
  dependencies:
  - gpg1
  description: Create and update encrypted content or decrypt encrypted content in
    YAML files
  homepage: https://github.com/Everbridge/generate-secure-pillar
  skip_upload: true
scoop:
  commit_author:
    name: goreleaserbot
    email: goreleaser@carlosbecker.com
builds:
- goos:
  - windows
  - darwin
  - linux
  goarch:
  - amd64
  goarm:
  - "6"
  targets:
  - windows_amd64
  - darwin_amd64
  - linux_amd64
  main: .
  ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
  binary: generate-secure-pillar
  lang: go
archive:
  name_template: '{{ .Tag }}-next'
  replacements:
    amd64: x86_64
    darwin: Darwin
    linux: Linux
    windows: Windows
  format: tar.gz
  files:
  - licence*
  - LICENCE*
  - license*
  - LICENSE*
  - readme*
  - README*
  - changelog*
  - CHANGELOG*
nfpm:
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm
    }}v{{ .Arm }}{{ end }}'
  formats:
  - deb
  - rpm
  dependencies:
  - gnupg1
  vendor: Everbridge, Inc.
  homepage: https://github.com/Everbridge/generate-secure-pillar
  maintainer: Ed Silva <ed.silva@everbridge.com>
  description: Create and update encrypted content or decrypt encrypted content in
    YAML files
  license: MIT
  bindir: /usr/local/bin
snapcraft:
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm
    }}v{{ .Arm }}{{ end }}'
snapshot:
  name_template: SNAPSHOT-{{.Commit}}
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
changelog:
  filters:
    exclude:
    - '^docs:'
    - '^test:'
  sort: asc
dist: packages
sign:
  cmd: gpg
  args:
  - -u
  - Everbridge Open Source
  - --output
  - ${signature}
  - --detach-sign
  - ${artifact}
  signature: ${artifact}.sig
  artifacts: checksum
env_files:
  github_token: ~/.config/goreleaser/github_token
github_urls:
  download: https://github.com
